=== zoozooll/MyExercise/com.company.hetuo_Android/assets/www/iweb_mall_0.9.8_ft/sysadmin/toolsBox/tool.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT toolbox (tool_item*)>
<!ELEMENT tool_item (toolName+,author,date,explain+,contentIndex+,contentAct+,programList+)>
<!ELEMENT toolName (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT explain (#PCDATA)>
<!ELEMENT contentIndex (#PCDATA)>
<!ELEMENT contentAct (#PCDATA)>
<!ELEMENT programList (#PCDATA)>
<!ATTLIST tool_item id ID #REQUIRED>

=== zoozooll/MyExercise/com.company.hetuo_Android/assets/www/iweb_mall_0.9.8_ft/sysadmin/toolsBox/tool.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE toolbox SYSTEM "tool.dtd">
<toolbox>


<tool_item id="clear_data">
		<toolName>删除数据工具</toolName>
		<author>dbojue</author>
		<date>2010-02-25</date>
		<explain>用于删除系统内的数据。</explain>
		<contentIndex>clear_data</contentIndex>
		<contentAct>clear_data.php</contentAct>
		<programList>clear_data.php</programList>
	</tool_item></toolbox>
